version: "3.9"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
      # target: dev # TODO dev 是啥意思？答：就是指定dockerfile文件的版本，会根据他选择不同的dockerfile
    volumes:
      - .:/opt/server
  site:
    build:
      dockerfile: Dockerfile
      context: ./site
      # target: dev # TODO dev 是啥意思？答：就是指定dockerfile文件的版本，会根据他选择不同的dockerfile
    volumes:
      - .:/opt/site